Document: mconf-chat
Title: Debian mconf-chat Manual
Author: Mauricio Cruz
Abstract: This manual describes what mconf-chat is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/mconf-chat/mconf-chat.sgml.gz

Format: postscript
Files: /usr/share/doc/mconf-chat/mconf-chat.ps.gz

Format: text
Files: /usr/share/doc/mconf-chat/mconf-chat.text.gz

Format: HTML
Index: /usr/share/doc/mconf-chat/html/index.html
Files: /usr/share/doc/mconf-chat/html/*.html
